steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - calculate-metrics
      - --region=europe-west1
      - --runtime=python311
      - --source=./cloudfunctions/calculate_metrics
      - --entry-point=execute_function
      - --trigger-http
options:
  logging: CLOUD_LOGGING_ONLY
